PLANS = {
    "free": {
        "name": "Free",
        "price_monthly": 0,
        "price_yearly": 0,
        "limits": {
            "products": 10,
            "orders_per_month": 50,
            "stores": 1,
            "flows": 2,
            "ai_store_builder": False,
            "analytics": False,
            "custom_domain": False,
            "payment_providers": 1,
            "team_members": 1,
        },
    },
    "starter": {
        "name": "Starter",
        "price_monthly": 29,
        "price_yearly": 290,
        "stripe_price_id_monthly": "",
        "stripe_price_id_yearly": "",
        "limits": {
            "products": 100,
            "orders_per_month": 500,
            "stores": 3,
            "flows": 10,
            "ai_store_builder": True,
            "analytics": True,
            "custom_domain": False,
            "payment_providers": 2,
            "team_members": 3,
        },
    },
    "pro": {
        "name": "Pro",
        "price_monthly": 79,
        "price_yearly": 790,
        "stripe_price_id_monthly": "",
        "stripe_price_id_yearly": "",
        "limits": {
            "products": 1000,
            "orders_per_month": 5000,
            "stores": 10,
            "flows": -1,
            "ai_store_builder": True,
            "analytics": True,
            "custom_domain": True,
            "payment_providers": -1,
            "team_members": 10,
        },
    },
    "enterprise": {
        "name": "Enterprise",
        "price_monthly": 199,
        "price_yearly": 1990,
        "stripe_price_id_monthly": "",
        "stripe_price_id_yearly": "",
        "limits": {
            "products": -1,
            "orders_per_month": -1,
            "stores": -1,
            "flows": -1,
            "ai_store_builder": True,
            "analytics": True,
            "custom_domain": True,
            "payment_providers": -1,
            "team_members": -1,
        },
    },
}
